.TH card 1
.SH NAME
card \- change apache server root directory
.SH SYNOPSIS
.B card [\fB\-c\fR]
.IR file
.SH DESCRIPTION
.BR card
program change apache server root directory in linux systems. card name
stand for Change Apache Root Directory. Program get directory from user
and replace it in apache config files. These files are /etc/apache2/apache2.conf
and /etc/apache2/sites-avialable/000-default.conf
.SH OPTIONS
.TP
.BR \-c ", " \-\-current
change apache root directory to current directory.

without any parametr during execution time program ask for directory.
.SH BUGS
.PP
for valuable sites dont recomented to use this program. Because can cause 
security proglems and there are some bugs. This program did not tested in
all Linux distributions (only Debian based distro-Kali Linux).
.SH AUTHOR
.PP
ORKHAN ALIBAYLI
.SH CONTACT
.PP
for bug reporting or to ask any questions please
contact with 
.BR orxanelibeyli6@gmail.com

.SH COPYRIGHT
.PP 
Copyright 2020 ORKHAN ALIBAYLI. AZERBAIJAN, BAKU. 
.SH CREDITS
.PP
All right reserved by ORKHAN ALIBAYLI.
